-- Seed all 53 Berufsfelder
INSERT INTO berufsfelder (name, beschreibung, anzeige) VALUES
('Architektur', 'Architektur gestaltet Umwelt. Im Konsens zwischen Gesellschaft und Geschichte entwickeln Architekten Lösungen für die unterschiedlichsten Bauaufgaben. Die Bandbreite des Architekten verläuft vom Städtebau bis über den Entwurf, das Baumanagement, die Entwicklung von Konzepten für regenerative Energieverwendung, etc. Die Ausbildung reagiert mit unterschiedlichen Schwerpunkten auf die verschiedenen Schwerpunkte. Mehr Informationen am Berufsinformationstag.', true),
('Banking BWL im Dualem Studium', 'Steigt ein in die faszinierende Welt der Finanzen. Die Bank hat als Arbeitgeber einiges zu bieten – ein Job, der Spaß macht, der kommunikativ und nah an den Menschen in der Region ist. Entdecke neue Perspektiven, Ausbildungs- und Karrierechancen.', true),
('Bauingenieurwesen', 'Bauingenieure planen und berechnen Konstruktionen und Anlagen im Bauwesen. Dazu gehören die Aufstellung von statischen Berechnungen für Gebäude und Industriebauten, der Entwurf und die Planung von Verkehrsanlagen und Brücken sowie das Baumanagement.', true),
('Betriebswirtschaftslehre', 'Das BWL-Studium ist der klassische Weg zu einem Einstieg in die Wirtschaft. Vor den Erfolg haben die Götter den Schweiß gesetzt – und den NC. Mehr Informationen am Berufsinformationstag.', true),
('Biologie', 'Der Studiengang Biologie bietet dir die Möglichkeit, in die faszinierende Welt der lebendigen Organismen einzutauchen. Du erforschst die Vielfalt des Lebens, von der Zellbiologie über Ökologie bis hin zur Genetik.', true),
('Bundeswehr', 'Die Bundeswehr bietet vielfältige Möglichkeiten für Ausbildung, Studium oder Direkteinstieg, um Teil der Truppe zu werden und einen bedeutungsvollen Beitrag zur Sicherheit Deutschlands zu leisten.', true),
('Chemie / Chemieingenieurwesen', 'Verfahrens- oder Chemieingenieurinnen und -ingenieure: Nicht nur in der chemischen Industrie zu Hause. Die Bandbreite reicht von der Pharmazie über die Lebensmittelindustrie bis zur Energietechnik.', true),
('Digital Management Solutions', 'Wissen, wie man für jedes Problem eine (digitale) Lösung findet? Durch die Digitale Transformation steigt der Bedarf an Fachkräften, die technologische und betriebswirtschaftliche Kompetenzen vereinen.', true),
('Diplomfinanzwirt FH (im Dualem Studium)', 'Karriere in der Finanzverwaltung - alles andere als langweilig. Das duale Studium zum Diplomfinanzwirt verbindet Theorie und Praxis optimal.', true),
('Duales Studium', 'Doppelt durchstarten! Duales Studium - Studium und Praxis erleben und verbinden. Von BWL über Maschinenbau bis Informatik.', true),
('Elektrotechnik', 'Ingenieure der Elektro- und Informationstechnik beschäftigen sich mit der Entwicklung und Herstellung elektronischer Geräte und Systeme, von Mikrochips bis zu großen Energieversorgungsanlagen.', true),
('Erziehungswissenschaft / Pädagogik', 'Der Studiengang Erziehungswissenschaft/Pädagogik bietet dir die Möglichkeit, dich intensiv mit Bildungs- und Erziehungsprozessen auseinanderzusetzen.', true),
('Eventmanagement', 'Der Studiengang Eventmanagement bietet dir die Möglichkeit, deine Leidenschaft für Organisation und Kreativität zum Beruf zu machen.', true),
('Fit fürs Studium?', 'Durchstarten mit Durchblick! Worauf kommt es bei der Studienauswahl an, wie strukturiert sich ein Semester und welche Unterstützungsangebote gibt es?', true),
('Forstwissenschaft', 'Alle Welt redet von Nachhaltigkeit - wer hat sie erfunden? Die Forstwissenschaft in Deutschland, vor über 300 Jahren.', true),
('Fremdsprachen', 'Der Studiengang Fremdsprachen ermöglicht es dir, dein Interesse an verschiedenen Sprachen und Kulturen zu vertiefen und beruflich einzusetzen.', true),
('Germanistik / Literaturwissenschaften', 'Du interessierst dich für den Studiengang Germanistik und Literaturwissenschaften? In diesem Studium beschäftigst du dich intensiv mit der deutschen Sprache, Literatur und Kultur.', true),
('Gesundheitswissenschaften / Public Health', 'Den Gesundheitszustand ganzer Bevölkerungen erfassen? Vorrangiges Anliegen der Gesundheitswissenschaften ist die Analyse und Verbesserung der Gesundheit auf Bevölkerungsebene.', true),
('Grafik-/Kommunikationsdesign/Gestaltung', 'Was unterscheidet einen Mediengestalter von einem Grafik-Designer? Informationen zu kreativen Berufen im Bereich Design und Gestaltung.', true),
('Grundschullehramt', 'Mit dem Studium Grundschullehramt kannst du deine Begeisterung für Bildung und Kinder zum Beruf machen.', true),
('Humanmedizin', 'Das seit Jahrzehnten fest gefügte Berufsbild Arzt, aber auch die Medizinerausbildung befinden sich gegenwärtig in einem raschen Wandel. Informationen zu Zugangsvoraussetzungen, Studienablauf, Weiterbildungs- und Spezialisierungsmöglichkeiten.', true),
('Informatik/IT', 'Neben der theoretischen Informatik tritt die Informatik vielfach als Interdisziplin zur Unterstützung anderer Wissenschaftsbereiche auf, z.B. als Wirtschaftsinformatik oder Medieninformatik.', true),
('Innenarchitektur', 'Bei der Innenarchitektur werden Lebensräume für Menschen gestaltet. Dazu gehört neben den künstlerischen Aspekten auch technisches und wirtschaftliches Wissen.', true),
('Internat. Schüleraustausch mit Rotary', 'Jährlich beteiligen sich deutschlandweit mehr als 600 Jugendliche an dem von Rotary organisierten und finanzierten internationalen Schüleraustausch.', true),
('Journalismus/Klassische Medien', 'Wie wird man Journalist? Warum sollte man es überhaupt werden? Was kann man verdienen? Einblicke in den Medienberuf.', true),
('Jura - Anwalt / Richter', 'Du interessierst dich für den Studiengang Jura? In diesem Studium beschäftigst du dich intensiv mit Rechtswissenschaften und ihren vielfältigen Anwendungsgebieten.', true),
('Kreisverwaltung / öffentliche Verwaltung', 'Mehr als 4,5 Millionen Arbeitsplätze gibt es in Deutschland in der öffentlichen Verwaltung. Einblicke in die vielfältigen Karrieremöglichkeiten.', true),
('Kulturmanagement/Kunst/Museum', 'Das Spektrum an beruflichen Tätigkeitsfeldern im Bereich Kunst ist breit gefächert: Kunst wird geschaffen, vermittelt, gehandelt, gesammelt und bewahrt.', true),
('Lehramt - nicht Grundschule', 'Lehrer haben vormittags Recht und nachmittags frei? Einblicke in das Lehramtsstudium für weiterführende Schulen.', true),
('Marketing', 'Marketing beschäftigt sich mit der Analyse von Märkten, dem Verhalten von Kundinnen und Kunden sowie der Entwicklung von Strategien.', true),
('Mathematik - nicht Lehramt', 'Du interessierst dich für den Studiengang Mathematik? In diesem Studium tauchst du tief in die Welt der Zahlen, Strukturen und logischen Zusammenhänge ein.', true),
('Mode - Duale Ausbildung', 'Ob Bluse, Hemd oder Hose, starte deinen Berufsweg in der Modeindustrie. Erfahre alles über die duale Ausbildung in der Modebranche.', true),
('Mode - Studium Textil und Mode', 'Studieren in der Bekleidungsindustrie - von Modemanagement bis Nachhaltigkeit.', true),
('Musik und Kirchenmusik', 'Musik in der Kirche: Ein Beruf mit vielen Freiheiten. Kirchenmusiker und Kirchenmusikerinnen sind für die musikalische Gestaltung in Gemeinden verantwortlich.', true),
('Öffentlichkeitsarbeit/PR', 'Pressesprecher/innen gestalten die Kommunikation eines Unternehmens oder einer Institution mit Medien und Öffentlichkeit.', true),
('Pflegemanagement / intern. BA/MA', 'Pflege und Gesundheit / internationale Bachelor- und Masterstudiengänge: Die Herausforderungen im Gesundheitswesen erfordern akademisch qualifizierte Fachkräfte.', true),
('Pharmazie', 'Apotheker(in) / PTA / PKA, wer macht was? Hier erfahren Sie alles über die Aufgabenfelder von Apothekern und pharmazeutischen Berufen.', true),
('Physik', 'Zu verstehen, was die Welt im Innersten zusammenhält, ist sicher ein Traum, und genau diese Neugier treibt Physiker an.', true),
('Polizeidienst', 'Interessant, abwechslungsreich und ein Beruf mit Zukunft - Polizeikommissarin/Polizeikommissar.', true),
('Psychiatrie', 'Anhand der beruflichen Entwicklung des Referenten werden die aktuellen Ausbildungsmöglichkeiten im Bereich Psychiatrie und Psychotherapie vorgestellt.', true),
('Psychologie', 'Psychotherapie ist die nicht-medikamentöse Behandlung psychischer Störungsbilder. Informationen zu den verschiedenen Therapieverfahren und Berufsbildern.', true),
('Sozialarbeit / Sozialpädagogik', 'Soziale Arbeit versteht sich als Profession, die wissenschaftsfundiert versucht, praktische soziale Probleme zu lösen, zu lindern oder zu verhindern.', true),
('Soziologie', 'Die Soziologie ist eine Wissenschaft, die die Abläufe und Entwicklungen untersucht, die sich im gesellschaftlichen Zusammenleben der Menschen abspielen.', true),
('Sportwissenschaften', 'Das Hobby zum Beruf machen?! Im Seminar Sportwissenschaften geht es darum, einen Einblick in Studium und Berufsmöglichkeiten zu geben.', true),
('Stadtverwaltung Bachelor of Laws', 'Du suchst einen abwechslungsreichen Job und willst deine Stadt mitgestalten? Entdecke die vielfältigen Karrieremöglichkeiten in der Kommunalverwaltung.', true),
('Start up / Das eigene Unternehmen', 'Unternehmertum und Startups: Deine Idee, dein Weg! Als Unternehmer*in verwirklichst du deine eigenen Geschäftsideen und bist dein eigener Chef.', true),
('Steuerberater / Wirtschaftsprüfer', 'Als Steuerberater und Wirtschaftsprüfer bist du ein wichtiger Partner für Unternehmen und Privatpersonen in steuerlichen und wirtschaftlichen Fragen.', true),
('Theologie', 'Wenn du ein Interesse an Religion, spirituellen Fragen und dem Studium der biblischen Texte hast, könnte ein Theologiestudium das Richtige für dich sein.', true),
('Tiermedizin', 'Die Tiermedizin ist ein spannender Berufszweig, der sich mit der Gesundheit und Behandlung von Tieren beschäftigt.', true),
('Volkswirtschaftslehre', 'Du interessierst dich für den Studiengang Volkswirtschaftslehre? In diesem Studium beschäftigst du dich mit wirtschaftlichen Zusammenhängen auf gesellschaftlicher Ebene.', true),
('Vorsorge & Absicherung des Studiums', 'Die Möglichkeiten zu studieren sind so vielfältig wie nie. Angefangen bei der Studienplatzsuche bis hin zur finanziellen Absicherung.', true),
('Wirtschaftsinformatik', 'Du interessierst dich für Wirtschaft und Informatik? Dann könnte Wirtschaftsinformatik das Richtige für dich sein.', true),
('Zahnmedizin', 'Die Zahnmedizin ist ein spannender Studienberuf, der sich um die Gesundheit unserer Zähne kümmert.', true);
